name: Flask CI/CD to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: flake8 .

    - name: Run tests
      run: pytest

    - name: Copy files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "."
        target: ${{ secrets.EC2_PATH }}

    - name: SSH into EC2 and restart Gunicorn
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
         ssh ubuntu@${{ secrets.EC2_HOST }} "bash -c '
          cd ${{ secrets.EC2_PATH }}
          source venv/bin/activate
          pkill gunicorn || true
          nohup gunicorn -b 0.0.0.0:8000 app:app &
        '"
